stack:
    - [EE]

EE:
    type: Interaction
    base_link: panda_link0
    distal_link: tcp
    impedance_ref_link: tcp
    force_max:
        - 100000.0
        - 100000.0
        - 100000.0
        - 10000.0
        - 10000.0
        - 10000.0    
    stiffness:
        - 1000.0
        - 1000.0
        - 1000.0
        - 100.0
        - 100.0
        - 100.0
    damping:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0